services:
  taskmanagerdb:
    image: mysql:8.0.41
    container_name: taskmanagerdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  dds.simpletaskmanager.api:
    image: ddssimpletaskmanagerapi
    container_name: ddssimpletaskmanagerapi
    build:
        context: ./backend
        dockerfile: ./DDS.SimpleTaskManager.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_HTTP_PORTS=${API_PORT}
        - ConnectionStrings__TaskManagerDbConnection=Server=taskmanagerdb;Database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;
    ports:
        - "${API_PORT}:${API_PORT}"
    depends_on:
        taskmanagerdb:
            condition: service_healthy
    restart: unless-stopped
    networks:
        - app-network

  dds.simpletaskmanager.frontend:
    image: ddssimpletaskmanagerfrontend
    container_name: ddssimpletaskmanagerfrontend
    build:
        context: ./frontend/SimpleTaskManager
        dockerfile: ./Dockerfile
        args:
          - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
        - "${FRONTEND_PORT}:80"
    depends_on:
        dds.simpletaskmanager.api:
            condition: service_started
    restart: unless-stopped
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local