services:
  taskmanagerdb:
    image: mysql:8.0.41
    container_name: taskmanagerdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaskManagerDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin123?
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-pAdmin123?"]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  dds.simpletaskmanager.api:
    image: ddssimpletaskmanagerapi
    container_name: ddssimpletaskmanagerapi
    build:
        context: ./backend
        dockerfile: ./DDS.SimpleTaskManager.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ConnectionStrings__TaskManagerDbConnection=Server=taskmanagerdb;Database=TaskManagerDB;Uid=admin;Pwd=Admin123?;AllowPublicKeyRetrieval=True;
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        taskmanagerdb:
            condition: service_healthy
    restart: unless-stopped
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local